package com.adagency.addanad.modules.marketing;

import jakarta.persistence.*;
import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * Entity representing Campaign Progress and Marketing Analysis.
 * Stores campaign views, visible date ranges, progress tracking,
 * and links each analysis section directly to a client via client_id.
 */
@Entity
@Table(name = "CampaignAnalysisDB")
public class CampaignAnalysisDB {

    // Primary Key: analysis_id auto-incremented
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "analysis_id")
    private Long analysisId;

    // Foreign Key / Reference: connects this analysis portion to the specific client
    @Column(name = "client_id", nullable = false)
    private Long clientId;

    // Optional reference to the specific campaign being analyzed
    @Column(name = "campaign_id")
    private Long campaignId;

    // Name or title of the campaign being tracked
    @Column(name = "campaign_name")
    private String campaignName;

    // Total number of audience views/impressions received by the campaign
    @Column(name = "campaign_views")
    private Long campaignViews = 0L;

    // Total clicks or interactions generated by the campaign
    @Column(name = "clicks")
    private Long clicks = 0L;

    // The starting date when the campaign became visible to audiences
    @Column(name = "visible_start_date")
    private LocalDate visibleStartDate;

    // The ending date when the campaign concludes its visibility period
    @Column(name = "visible_end_date")
    private LocalDate visibleEndDate;

    // Progress description or percentage (e.g. "70% Completed", "In Progress", "Concluded")
    @Column(name = "campaign_progress")
    private String campaignProgress;

    // Marketing Analyst observations, remarks, or optimization recommendations
    @Column(name = "remarks", columnDefinition = "TEXT")
    private String remarks;

    // Record creation timestamp
    @Column(name = "created_at")
    private LocalDateTime createdAt;

    public CampaignAnalysisDB() {
    }

    public CampaignAnalysisDB(Long clientId, Long campaignId, String campaignName, Long campaignViews,
                              LocalDate visibleStartDate, LocalDate visibleEndDate, String campaignProgress, String remarks) {
        this.clientId = clientId;
        this.campaignId = campaignId;
        this.campaignName = campaignName;
        this.campaignViews = campaignViews != null ? campaignViews : 0L;
        this.clicks = 0L;
        this.visibleStartDate = visibleStartDate;
        this.visibleEndDate = visibleEndDate;
        this.campaignProgress = campaignProgress;
        this.remarks = remarks;
        this.createdAt = LocalDateTime.now();
    }

    @PrePersist
    protected void onCreate() {
        if (this.createdAt == null) {
            this.createdAt = LocalDateTime.now();
        }
        if (this.campaignViews == null) {
            this.campaignViews = 0L;
        }
        if (this.clicks == null) {
            this.clicks = 0L;
        }
    }

    // Getters and Setters
    public Long getAnalysisId() {
        return analysisId;
    }

    public void setAnalysisId(Long analysisId) {
        this.analysisId = analysisId;
    }

    public Long getClientId() {
        return clientId;
    }

    public void setClientId(Long clientId) {
        this.clientId = clientId;
    }

    public Long getCampaignId() {
        return campaignId;
    }

    public void setCampaignId(Long campaignId) {
        this.campaignId = campaignId;
    }

    public String getCampaignName() {
        return campaignName;
    }

    public void setCampaignName(String campaignName) {
        this.campaignName = campaignName;
    }

    public Long getCampaignViews() {
        return campaignViews;
    }

    public void setCampaignViews(Long campaignViews) {
        this.campaignViews = campaignViews;
    }

    public Long getClicks() {
        return clicks;
    }

    public void setClicks(Long clicks) {
        this.clicks = clicks;
    }

    public LocalDate getVisibleStartDate() {
        return visibleStartDate;
    }

    public void setVisibleStartDate(LocalDate visibleStartDate) {
        this.visibleStartDate = visibleStartDate;
    }

    public LocalDate getVisibleEndDate() {
        return visibleEndDate;
    }

    public void setVisibleEndDate(LocalDate visibleEndDate) {
        this.visibleEndDate = visibleEndDate;
    }

    public String getCampaignProgress() {
        return campaignProgress;
    }

    public void setCampaignProgress(String campaignProgress) {
        this.campaignProgress = campaignProgress;
    }

    public String getRemarks() {
        return remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
}
